
/**
 * PQC Node.js compatibility module
 *
 * This file creates a compatible structure for Post-Quantum Cryptography (PQC) modules
 * in the Node.js environment that matches what's available in browser environments.
 *
 * It's needed because @noble/post-quantum doesn't support importing the whole module directly
 * (as seen in the error "root module cannot be imported: import submodules instead").
 *
 * This adapter imports the individual submodules and combines them into a single
 * object structure that matches what the browser bundle creates, ensuring chainpad-crypto
 * works consistently across both environments.
 *
 * In browser environments, the PostQuantum object is created by the bundled file
 * at /components/@noble/post-quantum/index.js (generated by scripts/pqc-browser-convert.js)
 */

const ml_kem = require('@noble/post-quantum/ml-kem');
const ml_dsa = require('@noble/post-quantum/ml-dsa');
const utils = require('@noble/post-quantum/utils');

module.exports = { ml_kem, ml_dsa, utils };
